dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "azelgaletal18"
    token:
      secure: "H0PeBhPWzpHc1ywNAuULirVdmHx7Iy9R4+CwZme/88n/Lr3QBhToupm4+az395T6NkkZUm3ZpZJgAgu75ydoqo3kr1h17pnKg3Cw8lA392FBiOEeMqoRzB2Xi7tyMvJOvCL7uMDRpZl2IqbKKRWGS7oDATDMNGyxz/RGb3Bkpdk9zU7033dQSDEnQA4Xm6+wDBkhfGi8XrR9+hlduYHI2UW/XBHK8Io/3XWGpf1K8SX9SO5ZuCdrj217MjYLH+AliuEHeWsVkhfMleGYBFpwJWCMsNMu/nTC9hbDCGWXhxF1R7kbHiGbRb7iNrgKR3CR0NOnlPEey1tJwvn8HCMqGuK/j1f2EWY9usrX+XW7qF654FfP28ALdV1/HGtU57acfIwHvNuU5DCwmzdX9RDGI+x81tfNYqEdIORu0xvCQT56yeU2TDdOLNmpBjeoZIuRPeU0wf7IEP2X/kwgnoS3a4+LUry3l//inT4T/BB2QoFMC56vpDBDmy7Ak4jgSkpcEc6pWJRorP+lFNjot4yT+GiO9rIVYQp6U4dL1ujasYU+N1LeBLR+3OnxW9fYy7A4XLYYFrEmEPB6Xt1X55X/6dZu6AeRp29Tzrg7gWOuYBmizXxpWp4W84+cx4dzwk+6aV+8/fTiny2U72zVX9AM5iV2YsAEWPFrCsLZYEYdMgQ="

install:
  - npm install

git:
  depth: false

script:
- mvn clean
- mvn verify
- mvn jacoco:report
- mvn install
- mvn package spring-boot:repackage
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AzelgaLetal18_SIGET_Equipo1


deploy: &heroku
        provider: heroku
        app: sigetequipo1
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde

server:
        port: $PORT
  
before_install:
  - chmod +x mvnw
